version: '3.9'

volumes:
  pgdata:

services:
  website:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./Django_project:/project
    depends_on:
      - postgresql
    env_file:
      - .env

  postgresql:
    image: 'postgres:12'
    environment:
      POSTGRES_DB: 'netology_stocks_products'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pstpwd'
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: 'nginx'
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Django_project/static:/var/www/html/static
    depends_on:
      - website
      - postgresql





