version: '3.9'

volumes:
  pgdata:
  static_files:

networks:
  backend:
  frontend:

services:
  website:
    build: .
    volumes:
      - static_files:/project/static
    depends_on:
      - postgresql
    env_file:
      - .env
    networks:
      - backend
      - frontend

  postgresql:
    image: 'postgres:12'
    environment:
      POSTGRES_DB: 'netology_stocks_products'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pstpwd'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    image: 'nginx'
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/var/www/html/static
    depends_on:
      - website
      - postgresql
    networks:
      - frontend





